estorefront/estorefront/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

from django.views.static import serve # Test to see if I can serve

from items.views import home, ItemToOptionsHandler, ItemListView, ItemDetailsView, EditItemDetailsView, CmsItemListView, CmsItemDetailsView, CMSItemUploadView, TestItemCMSView

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('items/', ItemListView.as_view(), name='items'),
    path('item/<int:item_id>', ItemDetailsView.as_view(), name='item'),
    path('cms_item/options', ItemToOptionsHandler.run, name='item_options'),
    # Nope
    path('cms_items/', CmsItemListView.as_view(), name='cms_items'),
    path('cms_item/<int:item_id>', EditItemDetailsView.as_view(), name='cms_item'),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Remove for production

estorefront/items/urls.py
from django.urls import path

import views

app_name = "items"
urlpatterns = [
    path("store", views.ItemListView.as_view(template_name="listeditem.html")),
    path("cms", views.ItemListView.as_view(template_name="cms_listeditem.html")),
    path("store/<int:item_id>", views.store_item, name="itemdetails")
]

estorefront/items/models.py
from django.db import models

pics_directory = "images/"

# Create your models here.

""" 
This represents an Item in the Store.

"""
class Item(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(unique=True)
    description = models.TextField(default="")
    price = models.PositiveIntegerField(default=0)


"""
This defines all possible options available

Universal Set
"""
class Option(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(unique=True)

""" 
This defines the various values for multi-choice items

If a value is not specified (Boolean choices) then there
should be no entry in this model.
"""
class OptionValue(models.Model):
    id = models.AutoField(primary_key=True)
    value = models.TextField(unique=True)

""" 
This links Options and their values to actual Items

Null optionvalue ForeignKey means that there is multiple choice for 
that option and it is instead a boolean choice or checkbox
"""
class ItemOptionValue(models.Model):
    # Neccessary only for linking multiple images to a single row (aka item/option/value tuple)
    id = models.AutoField(primary_key=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    option = models.ForeignKey(Option, on_delete=models.CASCADE)

    # Null Values here mean that the Option is a boolean 
    optionvalue = models.ForeignKey(OptionValue, on_delete=models.CASCADE, blank=True, null=True)
    
    # Simple Boolean field for determining if that option is available or not
    available = models.BooleanField(default=True, null=False)
    defaultoption = models.BooleanField(default=False, null=False)

    pricechange = models.IntegerField(default=0, null=False)

    class Meta:
        unique_together = ("item", "option", "optionvalue")

""" 
This table handles Pictures for a given Item/Option/Value tuple.

Necessary as a single tuple could have multiple Images
"""
class ItemOptionValueImage(models.Model):
    itemoptionvalue = models.ForeignKey(ItemOptionValue, on_delete=models.CASCADE)

    # This indicates the picture to use for the unique item/option/value tuple
    # Pictures are technically optional, but practically necessary
    photo = models.ImageField(upload_to=pics_directory, blank=True, null=True)

    class Meta:
        unique_together = ("itemoptionvalue", "photo")

estorefront/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block header %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

estorefront/templates/cms_itemdetails.html
{% extends "base.html" %}

{% block header %}
{% endblock %}

{% block content %}

<a href="{% url 'cms_items' %}">Back to Items</a>
</br>

<h4>Edit Data</h4>
<form id="edit_form" method="POST" action="/cms_upload">
    {% csrf_token %}
    <label>Name: </label><input name="name" type="text" value="{{ item.name }}"></br>
    <label>Description:</label></br><input name="description" value="{{ item.description }}" type="textarea"></br></br>
    {% if options|length > 0 %}
        <label>Options:</label></br>
        <ul>
            {% for key, elem in options.items %}
            <li>
                <div>
                    <p>{{ key }}</p>
                    {% for opt in elem %}
                    <input type="text" name="{{ opt.option__name }}" value="{{ opt.optionvalue__value }}">
                    <div>
                        <input type="checkbox" name="{{ opt.option__name }}.available" {% if opt.available %} checked="true" {% endif %}><label>Available</label>
                        <input type="checkbox" name="{{ opt.option__name }}.defaultoption" {% if opt.defaultoption %} checked="true" {% endif %}><label>Default</label>
                    </div>
                    {% endfor %}
                </div>
            </li>
            {% endfor %}
        </ul>
        <input type="submit" value="Submit">
    {% else %} 
    <p>No Options</p>
    {% endif %}

</form>

{% endblock %}

estorefront/templates/cms_listeditem.html
{% extends "base.html" %}

{% block header %}
{% endblock %}

{% block content %}

{% if item_list %}
<h1>Items</h1>
<ul>
    {% for item in item_list %}
    <li>
        <a href="{% url 'cms_item' item_id=item.id %}">
            <div>
                {{ item.name }}
            </div>
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Could not retrieve the list of Items</p>
{% endif %}

{% endblock %}

estorefront/templates/home.html
{% extends "base.html" %}

{% block header %}
{% endblock %}

{% block content %}
<h1>Testing Page</h1>
</br>
<p>This is for easy display for testing purposes.</p>
</br>
</br>
<a href="{% url 'items' %}">List of Test Item Display Views</a>
</br>
<a href="{% url 'cms_items' %}">List of Test Item Edit Views</a>
{% endblock %}

estorefront/templates/itemdetails.html
{% extends "base.html" %}

{% block header %}
{% endblock %}

{% block content %}

<a href="{% url 'items' %}">Back to Items</a>
</br>

<h3>{{ item.name }}</h3>
<p>{{ item.description }}</p>

{% if options|length > 0 %}
<ul>
    {% for key, elem in options.items %}
    <li>
        <div>
            <p>{{ key }}</p>
            {% for opt in elem %}
            <input {% if not opt.available %} disabled="true" onclick="this.checked=false" {% endif %} type="radio" name="{{ opt.option__name }}" value="{{ opt.id }}" {% if opt.defaultoption %} checked="true" {% endif %}><label {% if not opt.available %} style="color:lightgrey" {% endif %}>  {{ opt.optionvalue__value }}</label></br>
            {% endfor %}
        </div>
    </li>
    {% empty %}
    <li>Unable to Find Item and Options</li>
    {% endfor %}
</ul>
{% else %} 
<p>No Options</p>
{% endif %}

{% endblock %}

estorefront/templates/listeditem.html
{% extends "base.html" %}

{% block header %}
{% endblock %}

{% block content %}

{% if item_list %}
<h1>Items</h1>
<ul>
    {% for item in item_list %}
    <li>
        <a href="{% url 'item' item_id=item.id %}">
            <div>
                {{ item.name }}
            </div>
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Could not retrieve the list of Items</p>
{% endif %}

{% endblock %}

estorefront/templates/update_item.html
{% extends "base.html" %}

{% block header %}
{% endblock %}

{% block content %}

{{ context }}

{% endblock %}